# -*- coding: utf-8 -*-
"""Kopie von TASK_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a16SEOW-FwyQUV6C-XuhKsJsUHqkU_I5

# Task_1

# <font color='red'> 1) Mark down all the Valid boolean expression in python: </font> 

#### A) n > 100 and < 500
#### B) n > 100 and n < 500
#### C) 100 < n < 500
"""



A = False #@param {type:"boolean"} 
B = True #@param {type:"boolean"} 
C = True #@param {type:"boolean"}

"""
# <font color='red'> 2) Fill the gaps to get the ouput as in the example below:
##### (For any string greater than 3 characters)
#### **Input**: "globalization" 
#### **Output**: g11n
#### **
#### **Input**: "subjective" 
#### **Output**: s8e
#### **

### YOUR CODE: 
<font color='brown'> **s = input()** 
<br> **print(... + ... + ...)**
"""

s = input("enter a string: ")
print(s[0] + str(len(s)-2) + s[len(s)-1])

"""# <font color='red'> 3) Create a tuple of 10 elements and then multiply each element of the tuple by 2 & save the results in a list"""

total=[]
for element in ("2", "3","4", "5", "6", "7","8", "9" ,"1" ,"0"):
    total.extend(element * 2)

print(total)

"""# <font color='red'> 4) Reverse the string 'Mansoura' using slicing"""

s = 'Mansoura'
print(s[::-1])

"""# <font color='red'> 5) Use List Comprehension to create a list of the first letters of ever-y word in the string below:

* st = 'Friendship is the tree of its seeds tender'
"""

st = 'Friendship is the tree of its seeds tender'
list = st.split()
total = []
for element in list:
    firstLetter = element[0]
    total.append(firstLetter)
print(total)

"""# <font color='cyan'> BONUS <font color='red'> 6) Create a class called car that include some valriables like : 
* name
* color
* age
"""



"""# <font color='red'> **Solve these problems with python**:<br>
<a href='https://www.hackerrank.com/challenges/python-string-split-and-join/problem'> **problem 1**
    <br>
    <br>
<a href='https://www.hackerrank.com/challenges/py-if-else/problem'> **problem 2**
<br>
<br>
<a href='https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/Y'> **problem 3**
    <br>
    <br>
<a href='https://www.hackerrank.com/challenges/list-comprehensions/problem'> **problem 4** <font color='cyan'> BONUS
    <br>
    <br>
<a href='https://www.hackerrank.com/challenges/swap-case/problem'> **problem 5** <font color='cyan'> BONUS
    <br>
    <br>
<a href='https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/X'> **problem 6** <font color='cyan'> BONUS
    <br>

"""

#problem 1 

def split_and_join(line):
   split = line.split(" ")
   join = "-".join(split)
   return(join)
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

#problem 2

num = input("Enter your integer: ")
 
if int(num) % 2 != 0:
    print("Weird")
elif  int(num) in range(2,6): 
    print("Not Weird")
elif  int(num) in range(6,21): 
    print("Weird")
elif  int(num) > 20 : 
    print("Not Weird")

#problem 3

s = input("Enter 4 numbers: ")

s = s.split() 
s = "".join(s)
total = int(s[0]) * int(s[1]) * int(s[2]) * int(s[3]) 
total = str(total)
print(total[len(total)-2]+total[len(total)-1])

#problem 4

#problem 5

#problem 6